name: darkmoon-stack

volumes:
  zap-data: {}

services:

  darkmoon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: darkmoon
    user: "0:0"
    volumes:
      - ./prompt:/opt/darkmoon/prompt
      - ./scripts:/opt/darkmoon/scripts 
      - ${HOME}/darkmoon-docker-fs:/opt/darkmoon/zap_cli_out
      - ${HOME}/darkmoon-docker-fs:/opt/darkmoon/out
      - zap-data:/zap/wrk:ro
      - ~/.kube:/root/.kube:ro
    cap_add:
      - NET_RAW
      - NET_ADMIN
    environment:
      - DM_MODE=default
    restart: unless-stopped
